apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: lowconnectionpool-dr
spec:
  host: lowconnectionpool-service
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 1
      http:
        http1MaxPendingRequests: 1
        maxRequestsPerConnection: 1
