apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: svc2-rule
spec:
  host: service2
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
  subsets:
  - name: v1
    labels:
      version: v1
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
