apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: consistenthash-by-param
spec:
  host: service2
  trafficPolicy:
    loadBalancer:
      consistentHash:
        httpQueryParameterName: "uid" # the hash will be calculated based on request param  that will be passed by curl
  subsets:
    - name: all # custom name
      labels:
        app: service2 # app label we used in our deployment