apiVersion: v1
kind: ConfigMap
metadata:
  name: outlierservice-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! welcome to use outlier service </h1>
    </html>

  nginx.conf: |
    user nginx;
    worker_processes  2;
    events {
      worker_connections  1024;
    }
    http {

      include       mime.types;
      default_type  application/octet-stream;

      server {
          listen       80;
          server_name  localhost;

          location /500 {
             return 500 "<b>Whoa! trigger 500 outlier.</b>";
          }    
        
      }

    }