apiVersion: v1
kind: Service
metadata:
  name: service1
  namespace: default
spec:
  selector:
    app: service1
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30001
      targetPort: 80