apiVersion: v1
kind: ConfigMap
metadata:
  name: service1-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! welcome to use service 1 </h1>
    </html>

  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10;
    }
    http {

      include       mime.types;
      default_type  application/octet-stream;

      server {
          listen       80;
          server_name  localhost;

          location /svc2 {
            proxy_pass http://service2.default.svc.cluster.local/;
            # note this slash  ---------------------------------^ or will forward path /svc2 again
            proxy_http_version 1.1; # Istio 使用 Envoy 作为数据面转发 HTTP 请求，而 Envoy 默认要求使用 HTTP/1.1 或 HTTP/2，当客户端使用 HTTP/1.0 时就会返回 426 Upgrade Required。
          }

          location /svc2_change_source_ip {
            proxy_bind $remote_addr transparent;
            proxy_pass http://service2.default.svc.cluster.local/;
            # note this slash  ---------------------------------^ or will forward path /svc2 again
            proxy_http_version 1.1; # Istio 使用 Envoy 作为数据面转发 HTTP 请求，而 Envoy 默认要求使用 HTTP/1.1 或 HTTP/2，当客户端使用 HTTP/1.0 时就会返回 426 Upgrade Required。
          }

          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
          }    
        
      }

    }