apiVersion: v1
kind: ConfigMap
metadata:
  name: service2-configmap
  namespace: default
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>Hi! welcome to use service 2 </h1>
    </html>

  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10;
    }
    http {

      include       mime.types;
      default_type  application/octet-stream;

      server {
          listen       80;
          server_name  localhost;

          location / {
            root   /usr/share/nginx/html; #Change this line
            index  index.html index.htm;
          }    
        
      }

    }