apiVersion: apps/v1
kind: Deployment
metadata:
  name: service2v2-deploy
  namespace: default
spec:
  selector:                     # 定义 Deployment 如何查找要管理的 Pods
    matchLabels:
      app: service2
      version: v2
  template:
    metadata:
      labels:
        app: service2
        version: v2
    spec:

      containers:

      - name: service2-container
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes:
      - name: nginx-index-file
        configMap:
          name: service2v2-configmap
      - name: nginx-config
        configMap:
          name: service2v2-configmap
