apiVersion: v1
kind: Service
metadata:
  name: service2
  namespace: default
  labels:
    app: service2
spec:
  selector:
    app: service2
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 30002
      targetPort: 80
